### ISSUE TITLE
[Compatibility] Raised compat request

### ISSUE THREAD

**Issue by Estrelaura** [KrLite/Verticality#1]
The little arrow that makes the bar vertical doesn't get raised by the same amount as the hotbar when raised is installed. Would compat be simple enough?

**Comment by KrLite** [comment]
Thanks for reporting! I infer that it wouldn't be hard to compat. I'll figure out how **Raised** work soon.

**Comment by KrLite** [comment]
Fixed in [`v1.4.0`](https://modrinth.com/mod/verticality/version/1.20-v1.4.0)!

**Comment by KrLite** [comment]
![image](https://github.com/KrLite/Verticality/assets/68179735/9bee1518-cf23-43cb-892a-a6e0376f0c53)
