### ISSUE TITLE
[Compatibility] Doesn't Work with Skyblocker and Wynntils

### ISSUE THREAD

**Issue by ghost** [KrLite/Verticality#11]
basically this image:
![image](https://github.com/KrLite/Mod.Verticality/assets/140964974/3a8d3175-a106-460d-8a30-4a58ec515dfe)
sop what happens is that the bar hud is still at the middle, which i would nsay makes sense, but then the item rarity and slot locking is stuck in the middle.
here is the mod: https://github.com/SkyblockerMod/Skyblocker

**Comment by KrLite** [comment]
It's an interesting mod. I will consider to make it compatible in the next release!

**Comment by ghost** [comment]
ty

**Comment by Finsider** [comment]
The same thing also happened with Wynntils!
![2024-02-04_14 19 57](https://github.com/KrLite/Mod.Verticality/assets/91471471/56056eb0-2384-4123-8230-4ede26b2a07f)

**Comment by KrLite** [comment]
After tries, I found these mods are... simply too hard to compatible with. They customized the hotbar layout so much that I need to re-apply all the vertical and alternative offsets again and again to cover them all (and some of them are even not in vanilla 16x pixels).

And that is quite unacceptable. So I won't add compatibilities for mods that have too highly customized hotbars, also in the future.

Have good games though!
