### ISSUE TITLE
Server' /title overlapping

### ISSUE THREAD

**Issue by Finsider** [KrLite/Verticality#12]
![2024-02-04_14 23 48](https://github.com/KrLite/Mod.Verticality/assets/91471471/4000307e-b927-40fb-9c8e-2b8c4e7d44b9)
This happen when the hotbar is vertical. doesn't happen in horizontal mode.

**Comment by Finsider** [comment]
fantastic mods btw! I did not expect the mod to be so smooth.
The thing I would like to see is for the mod to allow wynntils' health bar to be used when the hotbar is in the corner. (because wynntils cannot use the health icon from verticality)

**Comment by KrLite** [comment]
😂 That must be my messing up on fixing some widgets’ positions. This will be fixed in the next release, and compatibility with wynntils will also be considered.
Thanks for loving this mod!

**Comment by KrLite** [comment]
Fixed in [`4.0.1`](https://modrinth.com/mod/verticality/version/4.0.1-mc1.20.2).
