### ISSUE TITLE
[Feature Request] Alternative Layout on 1.20~1.20.1

### ISSUE THREAD

**Issue by OlaPessoa** [KrLite/Verticality#14]

**Comment by KrLite** [comment]
Ok... It requires nothing but repetitive work to handle hud textures correctly and back port the alternative layout to 1.20.1. So, I'll do it when I have enough time. Releases are next month, probably.

**Comment by OlaPessoa** [comment]
Thank you for your support, and also sorry for the late response, i'll be waiting until next month very happily, this mod is so good, pure perfection, it's like the perfect portrait of a minecrafty-like RPG would have as a HUD

**Comment by OlaPessoa** [comment]
i'm so eager for this, just 3 days passed and i keep checking everyday, i need to learn how to code asap, i'd gladly port mods for newer versions for other mod devs if i knew how to, specially if they are this good, hopefully within learning java i'll be able to help!

**Comment by KrLite** [comment]
> i'm so eager for this, just 3 days passed and i keep checking everyday, i need to learn how to code asap, i'd gladly port mods for newer versions for other mod devs if i knew how to, specially if they are this good, hopefully within learning java i'll be able to help!

Sure. But please wait for a short term as I'm having school exams these days 😭

**Comment by OlaPessoa** [comment]
Nono, i know you have your life, i'm just so anxious, i love modding so much LOL, but take your time, i can assure you i did not say this to put pressure, it's quite the other way around, i actually do respect and love modders a lot, to the point i dream about becoming one, literally going to learn java so i can work with it and also MAINLY because of the hobby of modding

**Comment by KrLite** [comment]
It's [available now](https://modrinth.com/mod/verticality/version/4.1.3-fabric1.20) with some bug fixes. Hope you enjoy it!

**Comment by OlaPessoa** [comment]
sorry for the late response, THANK YOU <3 I LOVE YOU SO MUCH!!
