### ISSUE TITLE
[BUG] The Heart Doesn't Show Up

### ISSUE THREAD

**Issue by OlaPessoa** [KrLite/Verticality#15]
is there any known incompatabilities with this mod? 
![image](https://github.com/KrLite/Mod.Verticality/assets/119851799/ca4cf434-ebff-49a0-ac59-00c8d231d711)
; - ; why is the heart missing?? i've used both the latest version on top of the fabulously optimized modpack and also the 4.0.2 version and... for some reason the heart just simply does not show up??? everything works perfectly fine aside of that tho

**Comment by KrLite** [comment]
> is there any known incompatabilities with this mod? 
> 
> ![image](https://github.com/KrLite/Mod.Verticality/assets/119851799/ca4cf434-ebff-49a0-ac59-00c8d231d711)
> 
> ; - ; why is the heart missing?? i've used both the latest version on top of the fabulously optimized modpack and also the 4.0.2 version and... for some reason the heart just simply does not show up??? everything works perfectly fine aside of that tho

The mod does have some incompatibilities, but the heart shouldn't be missing though.

Could you please test it in a blank version without any other mod and resource pack loaded and see if the heart appears? If it doesn't, then it would be a bug and I'll fix that.

PS: Please provide your Minecraft version too! Some bugs only appear in certain versions.

**Comment by awenwraig** [comment]
experiencing the same issue on the newest version of the mod, 4.1.1, playing on 1.20.4
I verified that none of my resource packs modify the heart sprites, and none of the mods that I am using mention touching the HUD at all, only the inventory screens.
![2024-04-29_15 23 34](https://github.com/KessokuTeaTime/Verticality/assets/168384608/e6754579-5f87-43e8-ae88-97e7902aa353)

**Comment by KrLite** [comment]
This was caused by a forgotten access widener file. Fixed in [`4.1.2`](https://modrinth.com/mod/verticality/version/4.1.2-fabric1.20.2).
