### ISSUE TITLE
[BUG]: 1.20.4 Offhand Crash

### ISSUE THREAD

**Issue by awenwraig** [KrLite/Verticality#16]
### Mod Loader

Fabric

### Minecraft Version

1.20.4

### What Happened?

When moving an item to the offhand, the game crashes.

### Steps to Reproduce

Place item into offhand

### Crash Log

https://mclo.gs/7mZ3K7v

**Comment by KrLite** [comment]
Fixed in [`4.1.1`](https://modrinth.com/mod/verticality/version/4.1.1-fabric1.20.2).
