### ISSUE TITLE
[BUG]: Hey, it's me again! (This time the offhand slot doesn't want to show up ; -;)

### ISSUE THREAD

**Issue by OlaPessoa** [KrLite/Verticality#17]
### Mod Loader

Forge

### Minecraft Version

1.20.1

### What Happened?

welp 
![2024-05-07_08 04 56](https://github.com/KessokuTeaTime/Verticality/assets/119851799/4c1aebd7-fe67-4753-9e8e-f2ca3d244d83)
![2024-05-07_08 05 05](https://github.com/KessokuTeaTime/Verticality/assets/119851799/8885808a-ab2e-46f8-8365-61c96ef5bf60)
it took me a while to make this bug report, since i didn't want to be a burden with ya, since you already literally re-made the mod for a different version just because i asked for it ^ ^` so yeah... i waited for a lil bit before actually deciding to report it 

### What Should Happen?

SHOW DA ITEM

### Steps to Reproduce

just pretty much offhand anything, anything wont show up on the offhand slot (and... just for further context, that maybe a conflicting issue related to something else i have on my modpack [it has +170 mods so i dunno] i'll try using the mod by itself on 1.20.1 and i'll edit this report again later)

**Comment by KrLite** [comment]
Thanks for reporting! It is weird as I cannot replicate this issue on a pure client only modded with **Verticality.**

<img width="966" alt="截屏2024-05-07 下午8 03 28" src="https://github.com/KessokuTeaTime/Verticality/assets/68179735/b4e9042f-f6b7-4fe1-acf3-25fc3c23df01">


If it's a compatibility issue, I will try my best to fix it. However, the more complicated it will be, the lower possibly it will be fixed.

**Comment by OlaPessoa** [comment]
Jeez, that was a fast answer, thank you! also yeah i figured it was probally a compability issue, probally ain't even worth trying to make the compat betwhen the mod that's causing the issue and your mod tbh, i'll just try to figure out which mod is messing with it, and remove it (hopefully it's not a major mod ; - ;)

**Comment by OlaPessoa** [comment]
Thank ya for the quick answer nonetheless! as soon as i find out what it is, i'll remove it from the modpack, and if it's a major mod that other people may bump into the same issue i'll share what is it, otherwise there's not much of a reason to bother that much about it, specially if it's only a smoll thing

**Comment by KrLite** [comment]
But anyway, feel free to submit any issue! It's feedback like yours that makes the mod better.
