### ISSUE TITLE
[Bug] Offhand item rendered at wrong spot with left hand mode on

### ISSUE THREAD

**Issue by Estrelaura** [KrLite/Verticality#2]
When using the left hand as the main hand in the skin configuration options, putting an item in the offhand will render the item in the GUI on the left side, while the box will be on the right side (as it should be). Tested on Minecraft 1.20.1, Quilt 0.19.4

**Comment by KrLite** [comment]
Thanks for reporting! Fixed in [`v1.4.1`](https://modrinth.com/mod/verticality/version/1.20-v1.4.1).
