### ISSUE TITLE
[BUG] Game crashes with sinytra and polytone on forge

### ISSUE THREAD

**Issue by damikdevil** [KrLite/Verticality#21]
### Mod Loader

Forge

### Minecraft Version

1.20.1

### What Happened?

game crashe when loading

### What Should Happen?

not crash?

### Steps to Reproduce

inlogs

### Anything Else?

[latest (2).log](https://github.com/user-attachments/files/17893013/latest.2.log)

**Comment by KrLite** [comment]
Sorry, but I don’t think it’s my responsibility to fix bugs that only occur on Sinytra Connector. Although I’m glad to see it run on Connector, but I simply don’t want to provide extra services for Forge.

However, we are having plans to make an official Forge port, so please wait.
