### ISSUE TITLE
[request]option to verticalize the entire bar (including hp, hunger and xp) + option for left/right side

### ISSUE THREAD

**Issue by KaitoK1D** [KrLite/Verticality#3]
the mod is almost great! More options would bring this mod to the next level!

**Comment by KrLite** [comment]
Thanks for your idea! That sounds interesting and perhaps it will be considered in the next version.

**Comment by KrLite** [comment]
Actually this would be a little hard to achieve, otherwise the compatibility will be miserably bad (for example to compatible with appleskin). Therefore, this issue is going to be closed as not planned, as the features are not very practical. Thanks for suggesting though.
