### ISSUE TITLE
[2.0.1 | BUG] There is 3 bars that doesn't moving as intended

### ISSUE THREAD

**Issue by OKA-TAi** [KrLite/Verticality#5]
Uhh, i'm sorry for bothering you right after previous issue, but filled part of EXP / Horse jump bar with level is not moving... Don't need to rush yourself for this one, i can wait if needed!

Screenshots provided: https://imgur.com/a/u715tlv

**Comment by KrLite** [comment]
That is quite strange.

**Comment by KrLite** [comment]
Fixed in [`2.0.2`](https://modrinth.com/mod/verticality/version/2.0.2-mc1.20.2).
