### ISSUE TITLE
[2.0.2 Request + BUG] Horse jump bar still doesn't working as intended + Request for compability with Appleskin's Saturation bar

### ISSUE THREAD

**Issue by OKA-TAi** [KrLite/Verticality#6]
Hello, 2.0.1 fixed the filled EXP bar, but in 2.0.2 filled Horse bar still doesn't working as intended, even after being tested in isolated client (A.k.a. only Fabric API + Verticality)

Also i want to request a compability with Appleskins Saturation bar if possible, but not required, but still - thank you for all of your job!
 
Screenshots of BUG + REQUEST provided: https://imgur.com/a/WlORheF

**Comment by KrLite** [comment]
Okay

**Comment by KrLite** [comment]
Fixed in [`2.1.0`](https://modrinth.com/mod/verticality/version/8knZGn5f).
