### ISSUE TITLE
[REQUEST] Verticalized Health, Hunger & Experience Bars

### ISSUE THREAD

**Issue by Specimen-420** [KrLite/Verticality#7]
like this: https://legacy.curseforge.com/minecraft/mc-mods/vertical-hotbar

**Comment by KrLite** [comment]
It looks cool!

This feature will be considered, but as the scoreboard is occupying the right edge and the boss bar is on the top, Vertically will only allow you to put your hotbar at the left edge (or corner).

Also, the current layout of Verticality permits the max compatibility, but the corner layout will break some of them. For example, the compatibility with AppleSkin. And it's not easy to migrate the animations too :(

I'll try it when I'm spare and feel free to suggest more.

**Comment by KrLite** [comment]
I just found that the mod Vertical Hotbar was called Verticality too 4 years ago. WHAT?

**Comment by KrLite** [comment]
Check it [here!](https://modrinth.com/mod/verticality/version/3.0.0-mc1.20.2)
