### ISSUE TITLE
[Bug] Chat tooltip offset

### ISSUE THREAD

**Issue by ghost** [KrLite/Verticality#8]
![2024-01-03_15 57 12](https://github.com/KrLite/Verticality/assets/95710733/32127bd2-5fe2-412d-86e4-b21f7f384c64)

My cursor is over "/rules" in the chat, but the tooltip is from my username on the first line.
This happens with both corner orientations.

**Comment by KrLite** [comment]
I must have forgotten to apply the offsets to the hoverable areas. I will figure that out soon.

**Comment by KrLite** [comment]
By the way, what do you think of the new layouts :)

**Comment by ghost** [comment]
They look good.
