### ISSUE TITLE
[Bug] Double level indicator with ImmediatelyFast

### ISSUE THREAD

**Issue by ghost** [KrLite/Verticality#9]
![2024-01-03_16 15 02](https://github.com/KrLite/Verticality/assets/95710733/f62c46ea-47f6-4da8-9ce6-40fa21ad1ff0)
Using the mod with [https://github.com/RaphiMC/ImmediatelyFast](url) causes the level number to be rendered twice if the player has  >0 levels.

**Comment by KrLite** [comment]
Thanks for reporting. There are always infinite compatibility issues waiting to be fixed. 😇

**Comment by KrLite** [comment]
It is truly annoying in some ways so little tricks are needed to skip this. This should be fixed in the upcoming release.
